<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Properties -->
  <xacro:property name="chassis_length" value="0.25"/>
  <xacro:property name="chassis_width" value="0.23"/>
  <xacro:property name="chassis_height" value="0.09"/>
  <xacro:property name="chassis_mass" value="1.0"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_thickness" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.05"/>
  <xacro:property name="wheel_offset_x" value="0.11"/>
  <xacro:property name="wheel_offset_y" value="0.115"/>
  <xacro:property name="wheel_offset_z" value="0.0"/>

  <!-- Materials -->
  <material name="white"><color rgba="1 1 1 1" /></material>
  <material name="orange"><color rgba="1 0.3 0.1 1"/></material>
  <material name="blue"><color rgba="0.2 0.2 1 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>

  <!-- Base -->
  <link name="base_link"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  <link name="base_footprint"/>

  <!-- Chassis -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 0"/>
  </joint>
  <link name="chassis">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

<!--- Left Wheels - -->
<joint name="left_front_wheel_joint" type="fixed">
  <parent link="chassis"/>
  <child link="left_front_wheel"/>
  <origin xyz="0.08 ${wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
</joint>
<link name="left_front_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <material name="blue"/>
  </visual>
</link>

<joint name="left_mid_wheel_joint" type="fixed">
  <parent link="chassis"/>
  <child link="left_mid_wheel"/>
  <origin xyz="0.0 ${wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
</joint>
<link name="left_mid_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <material name="blue"/>
  </visual>
</link>

<joint name="left_rear_wheel_joint" type="fixed">
  <parent link="chassis"/>
  <child link="left_rear_wheel"/>
  <origin xyz="-0.08 ${wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
</joint>
<link name="left_rear_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <material name="blue"/>
  </visual>
</link>

<!-- - Right Wheels - -->
<joint name="right_front_wheel_joint" type="fixed">
  <parent link="chassis"/>
  <child link="right_front_wheel"/>
  <origin xyz="0.08 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
</joint>
<link name="right_front_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <material name="blue"/>
  </visual>
</link>

<joint name="right_mid_wheel_joint" type="fixed">
  <parent link="chassis"/>
  <child link="right_mid_wheel"/>
  <origin xyz="0.0 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
</joint>
<link name="right_mid_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <material name="blue"/>
  </visual>
</link>

<joint name="right_rear_wheel_joint" type="fixed">
  <parent link="chassis"/>
  <child link="right_rear_wheel"/>
  <origin xyz="-0.08 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0"/>
</joint>
<link name="right_rear_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
    </geometry>
    <material name="blue"/>
  </visual>
</link>

</robot>