amcl:
  ros__parameters:
    # Ignoriert, da nur per Launch-Argumenten gesetzt:
    set_initial_pose: true
    always_reset_initial_pose: true

    # Scan-/Motion-Model & Resampling
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    resample_interval: 1

    # Laser‐Modell (Likelihood Field)
    laser_model_type: "likelihood_field"
    lambda_short: 0.1
    sigma_hit: 0.1
    z_hit: 0.9
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.1
    laser_likelihood_max_dist: 1.0
    laser_max_range: 12.0
    laser_min_range: -1.0
    max_beams: 60

    # Beam‐Skip (für schnellere Verarbeitung)
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    # Partikelfilter‐Settings
    min_particles: 500
    max_particles: 3000
    pf_err: 0.02
    pf_z: 0.995
    recovery_alpha_fast: 0.01
    recovery_alpha_slow: 0.001

    # Update‐Trigger
    update_min_d: -0.1
    update_min_a: -0.1

    # TF‐Broadcast & Toleranzen
    tf_broadcast: true
    transform_tolerance: 1.0

    # Topics & Frames
    scan_topic: scan
    map_topic: map
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
