twist_mux:
  ros__parameters:
    use_stamped: false
    cmd_vel_out: "/cmd_vel"
    
    topics:
      navigation:
        topic   : /cmd_vel_nav
        timeout : 0.5
        priority: 10

      teleop:
        topic   : /cmd_vel_teleop
        timeout : 0.5
        priority: 100
